
FROM rocker/rstudio:latest

RUN apt-get update -y \
 & apt-get install -y \
      build-essential \
      cmake \
	  libxml2-dev \
  & R -e 'install.packages(c("arrow", "data.table", "tidyverse", "dplyr", "tidyr", "purrr", "recipes", "workflows", "tidymodels", "rsample", "MASS", "tune", "parsnip", "yardstick", "ggplot2", "themis", "patchwork", "ggthemes"))'
RUN R -e 'install.packages("lme4")'